# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal_dnorm <- function(x, means, sds, eps) {
    .Call(`_rspdcpp_cal_dnorm`, x, means, sds, eps)
}

cpplinterp_ <- function(x, y, xout, maxgap = 99999L, locf = FALSE) {
    .Call(`_rspdcpp_cpplinterp_`, x, y, xout, maxgap, locf)
}

cpplinterp <- function(x, y, xout, maxgap = 99999L, locf = FALSE) {
    .Call(`_rspdcpp_cpplinterp`, x, y, xout, maxgap, locf)
}

approx_test <- function(calcurve, start_date, end_date) {
    .Call(`_rspdcpp_approx_test`, calcurve, start_date, end_date)
}

calibrate <- function(ages, error, calcurve, start_date, end_date, normalize = FALSE) {
    .Call(`_rspdcpp_calibrate`, ages, error, calcurve, start_date, end_date, normalize)
}

uncalibrate <- function(agegrid, prdens, calcurve, start_date, end_date, normalize = FALSE) {
    .Call(`_rspdcpp_uncalibrate`, agegrid, prdens, calcurve, start_date, end_date, normalize)
}

make_mat <- function(input_list) {
    .Call(`_rspdcpp_make_mat`, input_list)
}

print_list <- function(input_list) {
    .Call(`_rspdcpp_print_list`, input_list)
}

make_mat_order <- function(input_val, input_pos, start_date, end_date) {
    .Call(`_rspdcpp_make_mat_order`, input_val, input_pos, start_date, end_date)
}

make_spd <- function(input_val, input_pos, start_date, end_date) {
    .Call(`_rspdcpp_make_spd`, input_val, input_pos, start_date, end_date)
}

make_spd <- function(input_val, start_date, end_date) {
    .Call(`_rspdcpp_make_spd`, input_val, start_date, end_date)
}

